In [1]:
import  numpy as np 

In [3]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [8]:
# creating array in numpy
arr=np.array([[1,2,3],
            [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
#accessing array in numpy

arr=np.array([[1,2,3],
              [45,53,65],
              [34,76,56]])
print(arr)
arr2=arr[:2,::2]
print("first two rows and alternate columns (0 and 2):\n",arr2)

[[ 1  2  3]
 [45 53 65]
 [34 76 56]]
first two rows and alternate columns (0 and 2):
 [[ 1  3]
 [45 65]]


In [19]:
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])
print(a,b)
print ("Adding 1 to every element:", a + 1)
print ("\n sub  1 to every element:", b -1)

print(a.dtype)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]
Adding 1 to every element: [[2 3]
 [4 5]]

 sub  1 to every element: [[4 5]
 [6 7]]
int64


In [34]:
import sys 
py_list=[1,2,3,4,5]
np_arr=np.array(py_list)

print(f"python list size = {sys.getsizeof(py_list)} bytes")

print(f"Numpy array size  size = {sys.getsizeof(np_arr)} bytes")

python list size = 104 bytes
Numpy array size  size = 152 bytes


In [39]:
# array dimensions in numpy 
arr=np.array([[1,2,3,4,5],
            [6,7,8,9,3]])
print(arr,type(arr))


[[1 2 3 4 5]
 [6 7 8 9 3]] <class 'numpy.ndarray'>


In [41]:
arr2 = np.array([1,2,3,4,5,"siddharth"])
print(arr2,arr2.dtype,type(arr),arr2.shape)

['1' '2' '3' '4' '5' 'siddharth'] <U21 <class 'numpy.ndarray'> (6,)


In [58]:
# makeing array in in bulk 
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr,type(arr),arr.shape)

arr1=np.ones((5,5))

print(arr1)


[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> (3, 3)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [55]:
# reshaping array 
arr=np.array([[1,2,3],[5,6,7],[8,9,0]])
print(arr[1],)

# fancy index  
ind=[0,1,3]
print(ind)

[5 6 7]
[0, 1, 3]


In [60]:
arr=  np.array([3+5j])
arr1=np.array([4+5j])
print(arr+arr1)
print(arr,arr.dtype)

[7.+10.j]
[3.+5.j] complex128


In [80]:
# array indexing in numpy 
arr3d = np.array([
    [[1,2],[3,4],[5,6]],
    [[7,8],[9,10],[11,12]]
])
print(arr3d[1,1,1])


10


In [78]:
arr=np.array([[1,2],[23,4]])
print(np.mean(arr))

7.5
